CREATE TABLE test(a INT PRIMARY KEY, b INT, c INT);
select d from test;
INSERT INTO test VALUES (1, 22, 333);
INSERT INTO test VALUES (2, 11, 000);
INSERT INTO test VALUES (3, 33, 444);
INSERT INTO test VALUES (4, 00, 555);
INSERT INTO test VALUES (5, 00, 555);
INSERT INTO test VALUES (6, 22, 333);
UPDATE test SET b = b + 1 WHERE a = 6;
DELETE FROM test WHERE a = 6 and c = 333;
SELECT * from test;
SELECT c, b from test where a=1;
SELECT a from test order by c+b desc, a asec;
SELECT a from test order by c+b desc, a asec LIMIT 2 OFFSET 2;
SELECT a, a + c FROM test ORDER BY a * 3 * b DESC, b + c / 5 ASC;
SELECT b, c, MIN(a - b) FROM test GROUP BY c, b ORDER BY b+c;
SELECT a + 4 * b FROM test GROUP BY a, b ORDER BY a * b ASC, c - a / 2 DESC;
SELECT DISTINCT * FROM test ORDER BY a + 10 * b + c LIMIT 3;
SELECT DISTINCT b + c FROM test GROUP BY b + c ORDER BY b + c;
DROP TABLE test;
